// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Catalogue.Api.Data;

#nullable disable

namespace Service.Catalogue.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925171306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Service.Catalogue.Api.DTOs.ServiceCatalogueDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Endpoints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20dc5834-b9a9-4cee-86ba-16ee2b268f28"),
                            CreatedAt = new DateTime(2025, 9, 25, 17, 13, 5, 937, DateTimeKind.Utc).AddTicks(6638),
                            Endpoints = "[\"https://api.example.com/users\"]",
                            Lifecycle = "production",
                            Name = "User Management",
                            OwnerTeam = "Identity",
                            Tags = "[\"auth\",\"users\"]",
                            Tier = "gold",
                            UpdatedAt = new DateTime(2025, 9, 25, 17, 13, 5, 937, DateTimeKind.Utc).AddTicks(6721)
                        },
                        new
                        {
                            Id = new Guid("d36021ab-2982-4de1-834c-bb969382d526"),
                            CreatedAt = new DateTime(2025, 9, 25, 17, 13, 5, 937, DateTimeKind.Utc).AddTicks(6837),
                            Endpoints = "[\"https://api.example.com/payments\"]",
                            Lifecycle = "preprod",
                            Name = "Payments API",
                            OwnerTeam = "Finance",
                            Tags = "[\"payments\",\"finance\"]",
                            Tier = "silver",
                            UpdatedAt = new DateTime(2025, 9, 25, 17, 13, 5, 937, DateTimeKind.Utc).AddTicks(6837)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
